import 'dart:core';

const String splashscreen = '/SplashScreen';
const String loginscreen = '/Login';
const String homescreen = '/UserHomeScreen';
const String eventsscreen = '/EventsScreen';
const String neighbourchatscreen = '/NeighbourChatScreen';
const String chatavailbilityscreen = '/ChatAvailbilityScreen';
const String reporttoadmin = '/ReportToAdmin';
const String adminreports = '/AdminReports';
const String preapproveentryscreen = '/PreApproveEntryScreen';
const String addpreapproveentryscreen = '/AddPreApproveEntryScreen';
const String reportshistoryscreen = '/ReportsHistoryScreen';
const String guestshistoryscreen = '/GuestsHistoryScreen';
const String notificationsscreen = '/NotificationsScreen';
const String vieweventimages = '/ViewEventImages';
const String viewimage = '/ViewImage';
const String noticeboardscreen = '/NoticeBoardScreen';
const String gatekeeperreports = '/GatekeeperReports';
const String residentpersonaldetail = '/ResidentPersonalDetail';
const String residentaddressdetail = '/ResidentaddressDetail';
const String addfamilymember = '/AddFamilyMember';
const String viewfamilymember = '/ViewFamilyMember';
const String discussion_form = '/DiscussionForm';
const String monthly_bill = '/MonthlyBill';
const String marketPlaceScreen = '/MarketPlaceScreen';
const String sellProductsScreen = '/SellProductsScreen';
const String addEmergencyScreen = '/AddEmergencyScreen';
